### ISSUE TITLE
datapusher cannot startup with ckan-2.3.5/ckanext-bcgov-1.3.1 branch

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#135]
https://github.com/bcgov/datapusher startup failure
```python
Traceback (most recent call last):
  File "/etc/ckan/tst/datapusher.wsgi", line 12, in <module>
    import datapusher.jobs as jobs
  File "/tmp/bcdcsrc/src/datapusher/datapusher/jobs.py", line 19, in <module>
    import messytables
  File "/apps/ckan/tst/lib/python2.7/site-packages/messytables/__init__.py", line 21, in <module>
    from messytables.html import HTMLTableSet, HTMLRowSet
  File "/apps/ckan/tst/lib/python2.7/site-packages/messytables/html.py", line 4, in <module>
    import html5lib
  File "/apps/ckan/tst/lib/python2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/apps/ckan/tst/lib/python2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by ll911** [comment]
@gjlawran @kfishwick confirm this only effect ckanext-bcgov-1.3.1 with ckan-2.3.5-bcgov branch

**Comment by Mbrownshoes** [comment]
Datapusher is working in CAT
