### ISSUE TITLE
extension paster cmd broken

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#272]
```bash
paster --plugin=ckanext-bcgov edc_command --help
Traceback (most recent call last):
  File "/apps/ckan/dlv/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
    command = commands[command_name].load()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/apps/ckan/dlv/src/ckanext-bcgov/ckanext/bcgov/commands/edc_commands.py", line 28, in <module>
    class EdcCommand(CkanCommand):
  File "/apps/ckan/dlv/src/ckanext-bcgov/ckanext/bcgov/commands/edc_commands.py", line 46, in EdcCommand
    os.path.dirname(ckanext.bcgov.__file__),
AttributeError: 'module' object has no attribute '__file__'
```

**Comment by mdunhamwilkie** [comment]
Not sure that the expected behaviour is.  Putting this on hold for now.
