### ISSUE TITLE
In TEST, Navigating to a public OFI metadata record  as a public user gets Server Error.  As an IDIR authenticated user the record it does not.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#293]
The record in question is [pub-downloadofi](https://cat.data.gov.bc.ca/dataset/pub-downloadofi)

1. logout of test (if logged in)
2. in the left nav select **Geographic Datasets** under **Dataset types**
3. scroll down until you see [pub-downloadofi](https://cat.data.gov.bc.ca/dataset/pub-downloadofi) and click on it.

- I expect to view the metadata record.
- Instead i get:
![screen shot 2017-02-28 at 4 20 37 pm](https://cloud.githubusercontent.com/assets/3906047/23440634/005d2aa6-fdd2-11e6-9528-89ade57a7979.png)

4. login with an IDIR account
5. navigate to  [pub-downloadofi](https://cat.data.gov.bc.ca/dataset/pub-downloadofi)
6. The data record is displayed.
![screen shot 2017-02-28 at 12 24 50 pm](https://cloud.githubusercontent.com/assets/3906047/23440712/87372b80-fdd2-11e6-8209-a11238837ae9.png)

I don't know if it is related but i'm seeing the following in [edctst.log](https://test.apps.gov.bc.ca/ext/sgw/edclogs/edctst.log)
```
Error - <type 'exceptions.ValueError'>: Authorization function not found: populate_dataset_with_ofi
Traceback (most recent call last):
  File "/apps/ckan/tst/src/ckan/ckan/config/middleware.py", line 364, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/apps/ckan/tst/src/ckan/ckan/config/middleware.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 118, in __call__
    wrapper.finish_response(remember_headers)
  File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 178, in finish_response
    self.buffer.seek(0)
  File "/s00/lib64/python2.7/StringIO.py", line 112, in seek
    self.pos = max(0, pos)
  File "/apps/ckan/tst/lib/python2.7/site-packages/weberror/errormiddleware.py", line 171, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/apps/ckan/tst/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/apps/ckan/tst/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/apps/ckan/tst/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/apps/ckan/tst/src/ckan/ckan/config/middleware.py", line 389, in inner
    result = application(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
    response = self.app(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/apps/ckan/tst/src/ckan/ckan/controllers/api.py", line 70, in __call__
    return base.BaseController.__call__(self, environ, start_response)
  File "/apps/ckan/tst/src/ckan/ckan/lib/base.py", line 337, in __call__
    res = WSGIController.__call__(self, environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
    response = self._dispatch_call()
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/apps/ckan/tst/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/apps/ckan/tst/src/ckanext-bcgov/ckanext/bcgov/controllers/ofi.py", line 83, in action
    populate_results = action_func(context, data)
  File "/apps/ckan/tst/src/ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "/apps/ckan/tst/src/ckanext-bcgov/ckanext/bcgov/logic/ofi/__init__.py", line 31, in wrapper
    toolkit.check_access(action.__name__, context, data)
  File "/apps/ckan/tst/src/ckan/ckan/logic/__init__.py", line 283, in check_access
    data_dict)
  File "/apps/ckan/tst/src/ckan/ckan/authz.py", line 177, in is_authorized
    raise ValueError(_('Authorization function not found: %s' % action))
ValueError: Authorization function not found: populate_dataset_with_ofi
```
@Mbrownshoes

**Comment by dkelsey** [comment]
DELIVERY is showing another issues with OFI records.

**Steps:**
1. log out of DELIVERY
2. Filter on Geographic Datasets
3. click any OFI record
![screen shot 2017-03-01 at 8 54 40 am](https://cloud.githubusercontent.com/assets/3906047/23471020/cf46a7cc-fe5c-11e6-99bd-f4dff749271c.png)

**Expected:**
The record is displayed
**Actual:**
The page cannot be displayed.
![screen shot 2017-03-01 at 8 54 54 am](https://cloud.githubusercontent.com/assets/3906047/23471033/dba88896-fe5c-11e6-854d-dd555cf4324d.png)

from the delivery [`edctst.log`](https://delivery.apps.gov.bc.ca/ext/sgw/edclogs/edcdlv.log)
```
Debug at: https://cad.data.gov.bc.ca/_debug/view/1488386200
Traceback (most recent call last):
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/config/middleware.py", line 364, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
    return self.apps[-1](environ, start_response)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/config/middleware.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/repoze/who/middleware.py", line 118, in __call__
    wrapper.finish_response(remember_headers)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/repoze/who/middleware.py", line 178, in finish_response
    self.buffer.seek(0)
  File "/s00/lib64/python2.7/StringIO.py", line 112, in seek
    self.pos = max(0, pos)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/weberror/evalexception.py", line 428, in respond
    app_iter = self.application(environ, detect_start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/config/middleware.py", line 389, in inner
    result = application(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
    response = self.app(environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
    return controller(environ, start_response)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/lib/base.py", line 337, in __call__
    res = WSGIController.__call__(self, environ, start_response)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
    response = self._dispatch_call()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
    response = self._inspect_call(func)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
    return func(**args)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckanext-bcgov/ckanext/bcgov/controllers/package.py", line 191, in read
    c.ofi = _setup_ofi(pkg_dict['id'], context=context, pkg_dict=pkg_dict, open_modal=False)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckanext-bcgov/ckanext/bcgov/controllers/package.py", line 602, in _setup_ofi
    projections = get_action(u'crs_types')(context, {})
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/logic/__init__.py", line 416, in wrapped
    result = _action(context, data_dict, **kw)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/logic/__init__.py", line 532, in wrapper
    return action(context, data_dict)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckanext-bcgov/ckanext/bcgov/logic/ofi/__init__.py", line 31, in wrapper
    toolkit.check_access(action.__name__, context, data)
  File "/apps/cis/workspace/bcdc/BCDC/src/ckan/ckan/logic/__init__.py", line 286, in check_access
    raise NotAuthorized(msg)
ckan.logic.NotAuthorized: <function crs_types at 0x7f9405ccd320> requires an authenticated user
[pid: 13043|app: 0|req: 485/485] 142.34.140.32 () {46 vars in 2827 bytes} [Wed Mar  1 08:58:26 2017] GET /dataset/gjl-bcdc-1-6-test-in-cad-with-ofi-of-public-dataset => generated 0 bytes in 196 msecs (HTTP/1.1 500) 2 headers in 127 bytes (0 switches on core 3)
```

**Comment by ll911** [comment]
@dkelsey @jrods they all look like authorization logic related. error.

**Comment by jrods** [comment]
@dkelsey so the first error relates to a change I recently made regarding action calls mapping to an authorization function. I will submit a PR to fix the missing call.

As for the second error, `<function crs_types at 0x7f9405ccd320> requires an authenticated user`. Currently the crs_types call doesn't allow for anonymous users. 
Note*: This is also the same for getting file_formats, checking object_names, editing/removing ofi resources and getting the form for submitting an order.
@Mbrownshoes

**Comment by Mbrownshoes** [comment]
@jrods We're still not able to access publically viewable OFI records in cad. 

Currently the crs_types call doesn't allow for anonymous users. I'm not sure what crs_types does (thought it was the projection) but we need these records in cad viewable to unauthenticated users.

**Comment by jrods** [comment]
@Mbrownshoes Yes, the crs_types gets available projections from DWDS. I just want to be sure before removing any authorization checks. I'll submit a PR to allow for the crs_types to be called by anonymous users.

**Comment by Mbrownshoes** [comment]
@jrods gotcha. thanks

**Comment by Mbrownshoes** [comment]
@leo would like to investigate how this function is supposed to work before accepting the PR.
