### ISSUE TITLE
Unable to push to datastore in CAD

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#304]
we’re unable to push to the datastore in CAD, here is the error Upload error: An Error occurred while sending the job: 500 Server Error: Internal Server Error.

sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
could not create socket: Address family not supported by protocol

from @ll911 
the datastore connection string is stored within ckan.ini ckan.datastore.write_url and ckan.datastore.read_url

**Comment by Mbrownshoes** [comment]
datastore pg is not running on the default pg port 5432? did anyone change the ckan.ini file?
The datapusher failed to start.

**Comment by Mbrownshoes** [comment]
@jrods @kfishwick are you able to fix this today?

**Comment by kfishwick** [comment]
This should be assigned to @ll911  we did not update ckan.ini.

**Comment by ll911** [comment]
@kfishwick @jrods the datapusher failed to start with current master build
```python
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "/etc/ckan/dlv/datapusher.wsgi", line 10, in <module>
    web.init()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/ckanserviceprovider/web.py", line 51, in init
    init_scheduler(app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "/apps/ckan/dlv/lib/python2.7/site-packages/ckanserviceprovider/web.py", line 132, in init_scheduler
    sqlalchemy_store.SQLAlchemyJobStore(url=db_uri), 'default')
  File "/apps/ckan/dlv/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy_store.py", line 54, in __init__
    self.jobs_t.create(self.engine, True)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 648, in create
    checkfirst=checkfirst)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1554, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/s00/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1547, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1737, in contextual_connect
    self.pool.connect(),
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 332, in connect
    return _ConnectionFairy._checkout(self)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 630, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 433, in checkout
    rec = pool._do_get()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 949, in _do_get
    return self._create_connection()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 278, in _create_connection
    return _ConnectionRecord(self)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 404, in __init__
    self.connection = self.__connect()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 530, in __connect
    connection = self.__pool._creator()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
    connection_invalidated=invalidated
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not create socket: Address family not supported by protocol
 None None
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by kfishwick** [comment]
@ll911  this looks like infrastructure change are you sure it is related to ckan extension?

**Comment by ll911** [comment]
@kfishwick infrastructure has no changes, the change was moving jenkins deployment steps from jenkins job configuration to a Jenkinsfile in git, all the steps are remain the same, and I don't understand why it failed to initiate ```SQLALCHEMY_DATABASE_URI``` which is set already in ```ckan.ini```

**Comment by dkelsey** [comment]
This turned out to be an issue with the `datapusher` configuration.  it was resolved.
