### ISSUE TITLE
Data explorer not working in Cat, works in cad 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#416]
When viewing a csv resource for a dataset record the data explorer does not render and the following errors are observed. It does work in delivery.

![screen shot 2017-12-20 at 4 48 40 pm](https://user-images.githubusercontent.com/3362533/34235353-fdde1404-e5a5-11e7-83d0-6ffad7d96b83.png)
@dkelsey @jrods

**Comment by Mbrownshoes** [comment]
@jrods, @ll911 mentioned turning off SSL verfication.

**Comment by ll911** [comment]
firefox works, the error shows in chrome

**Comment by ll911** [comment]
this is related to https://github.com/ckan/ckan/issues/3921, only happen when using WSGI to serve CKAN, e.g. mod_wsgi, uWSGI, CAD is using pylon instead.

**Comment by ll911** [comment]
attached error logs on server
```
[Fri Dec 22 15:00:10.395631 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532] Traceback (most recent call last):
[Fri Dec 22 15:00:10.395650 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/s00/lib/python2.7/site-packages/mod_wsgi/server/__init__.py", line 1490, in handle_request
[Fri Dec 22 15:00:10.395688 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     return self.application(environ, start_response)
[Fri Dec 22 15:00:10.395699 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/cis/workspace/bcdc/bcdc-rc/src/ckan/ckan/config/middleware/__init__.py", line 136, in __call__
[Fri Dec 22 15:00:10.395721 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     return self.apps[app_name](environ, start_response)
[Fri Dec 22 15:00:10.395731 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/cis/workspace/bcdc/bcdc-rc/src/ckan/ckan/config/middleware/common_middleware.py", line 216, in __call__
[Fri Dec 22 15:00:10.395812 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     return self.app(environ, start_response)
[Fri Dec 22 15:00:10.395829 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/ckan/tst/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Fri Dec 22 15:00:10.395887 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     return self.apps[-1](environ, start_response)
[Fri Dec 22 15:00:10.395899 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/cis/workspace/bcdc/bcdc-rc/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
[Fri Dec 22 15:00:10.395916 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     return self.app(environ, start_response)
[Fri Dec 22 15:00:10.395927 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/ckan/tst/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Fri Dec 22 15:00:10.396056 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     app_iter = self.application(environ, start_response)
[Fri Dec 22 15:00:10.396069 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in __call__
[Fri Dec 22 15:00:10.396144 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     wrapper.finish_response(remember_headers)
[Fri Dec 22 15:00:10.396156 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]   File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
[Fri Dec 22 15:00:10.396172 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532]     write = self.start_response(self.status, headers, self.exc_info)
[Fri Dec 22 15:00:10.396189 2017] [wsgi:error] [pid 31156:tid 140275512551168] [remote 142.34.140.32:53532] TypeError: expected byte string object, value of type unicode found
```

**Comment by ll911** [comment]
work around is run with gunicorn

**Comment by ll911** [comment]
@Mbrownshoes please confirm

**Comment by Mbrownshoes** [comment]
working in cat

**Comment by jeff-at-h3** [comment]
Leo, can you please validate this in CAT?

**Comment by ll911** [comment]
fixed by switching to gunicorn, ckan core also has patch under 2.7.3 https://github.com/ckan/ckan/tree/ckan-2.7.3

**Comment by dkelsey** [comment]
This was about CAT and CAD.  PROD appears fine.  DataExplorer is working.
